apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: weightapp
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000